mqtt:
  host: 192.168.2.114
  port: 1883
  username: homeassistant
  password: azi9Hueyah0Ues1ra2Koh3atho8haph0eeMe6ihahweicohngeShu9oosh7aemai
  report_interval_seconds: 10

local:
  envoy_host: 192.168.2.98
  envoy_user: mh.joosten666@gmail.com
  envoy_password: 8FvFZeRg8Kd58Y
  envoy_serial: 122245035174

